/* Net Gyro_Project - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include "net_types.h"


#define ABS(x) (((x)>=0)?(x):-(x))


/* Array implementation: */


void createInitial_Gyro_Project_NetMarking( Gyro_Project_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_2 = 0; /* Place pl_Foward */
    init_marking->p_3 = 0; /* Place pl_Flying */
    init_marking->p_4 = 0; /* Place pl_Backward */
    init_marking->p_5 = 0; /* Place pl_left */
    init_marking->p_6 = 0; /* Place pl_right */
    init_marking->p_38 = 1; /* Place pl_Land */
    init_marking->p_46 = 0; /* Place pl_RotateLeft */
    init_marking->p_47 = 0; /* Place pl_RotateRight */
    init_marking->p_60 = 0; /* Place pl_Up */
    init_marking->p_67 = 0; /* Place pl_Down */
    init_marking->p_74 = 0; /* Place pl_TakeOff */
    init_marking->p_75 = 0; /* Place pl_Landing */
    init_marking->p_84 = 0; /* Place pl_takePhoto */
    init_marking->p_91 = 0; /* Place pl_Wait */
    init_marking->p_104 = 0; /* Place pl_Wait2 */
    init_marking->p_109 = 0; /* Place pl_Wait3 */
    init_marking->p_116 = 0; /* Place pl_Wait4 */
}

void createEmpty_Gyro_Project_NetMarking( Gyro_Project_NetMarking* empty_marking )
{
    empty_marking->p_2 = 0; /* Place pl_Foward */
    empty_marking->p_3 = 0; /* Place pl_Flying */
    empty_marking->p_4 = 0; /* Place pl_Backward */
    empty_marking->p_5 = 0; /* Place pl_left */
    empty_marking->p_6 = 0; /* Place pl_right */
    empty_marking->p_38 = 0; /* Place pl_Land */
    empty_marking->p_46 = 0; /* Place pl_RotateLeft */
    empty_marking->p_47 = 0; /* Place pl_RotateRight */
    empty_marking->p_60 = 0; /* Place pl_Up */
    empty_marking->p_67 = 0; /* Place pl_Down */
    empty_marking->p_74 = 0; /* Place pl_TakeOff */
    empty_marking->p_75 = 0; /* Place pl_Landing */
    empty_marking->p_84 = 0; /* Place pl_takePhoto */
    empty_marking->p_91 = 0; /* Place pl_Wait */
    empty_marking->p_104 = 0; /* Place pl_Wait2 */
    empty_marking->p_109 = 0; /* Place pl_Wait3 */
    empty_marking->p_116 = 0; /* Place pl_Wait4 */
}

void add_Gyro_Project_NetMarkings(
    Gyro_Project_NetMarking* dest_marking,
    Gyro_Project_NetMarking* source_marking )
{
    dest_marking->p_2 += source_marking->p_2; /* Place pl_Foward */
    dest_marking->p_3 += source_marking->p_3; /* Place pl_Flying */
    dest_marking->p_4 += source_marking->p_4; /* Place pl_Backward */
    dest_marking->p_5 += source_marking->p_5; /* Place pl_left */
    dest_marking->p_6 += source_marking->p_6; /* Place pl_right */
    dest_marking->p_38 += source_marking->p_38; /* Place pl_Land */
    dest_marking->p_46 += source_marking->p_46; /* Place pl_RotateLeft */
    dest_marking->p_47 += source_marking->p_47; /* Place pl_RotateRight */
    dest_marking->p_60 += source_marking->p_60; /* Place pl_Up */
    dest_marking->p_67 += source_marking->p_67; /* Place pl_Down */
    dest_marking->p_74 += source_marking->p_74; /* Place pl_TakeOff */
    dest_marking->p_75 += source_marking->p_75; /* Place pl_Landing */
    dest_marking->p_84 += source_marking->p_84; /* Place pl_takePhoto */
    dest_marking->p_91 += source_marking->p_91; /* Place pl_Wait */
    dest_marking->p_104 += source_marking->p_104; /* Place pl_Wait2 */
    dest_marking->p_109 += source_marking->p_109; /* Place pl_Wait3 */
    dest_marking->p_116 += source_marking->p_116; /* Place pl_Wait4 */
}

void init_Gyro_Project_OutputSignals(
    Gyro_Project_PlaceOutputSignals* place_out,
    Gyro_Project_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    place_out->Out_TakeOffLand = 0;
    place_out->Out_Foward = 0;
    place_out->Out_Backward = 0;
    place_out->Out_Left = 0;
    place_out->Out_Right = 0;
    place_out->Out_Up = 0;
    place_out->Out_Down = 0;
    place_out->Out_RotateLeft = 0;
    place_out->Out_RotateRight = 0;
    place_out->Out_TakePhoto = 0;
}

/* Transition 7 - tr_up */
int t_7_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_7_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_7_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Y > 4800 );
}

void t_7_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_7_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_4++;
}

void t_7_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 10 - tr_down */
int t_10_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_10_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_10_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Y < 3200 );
}

void t_10_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_10_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_2++;
}

void t_10_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 13 - tr_left */
int t_13_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_13_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_13_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_X < 3200 );
}

void t_13_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_13_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_5++;
}

void t_13_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 16 - tr_right */
int t_16_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_16_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_16_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_X > 4800 );
}

void t_16_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_16_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_6++;
}

void t_16_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 26 - tr_26 */
int t_26_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_4 >= 1 );
}

int t_26_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_26_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Y <= 4800 );
}

void t_26_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_4--;
}

void t_26_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_26_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 29 - tr_29 */
int t_29_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_6 >= 1 );
}

int t_29_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_29_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_X <= 4800 );
}

void t_29_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_6--;
}

void t_29_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_29_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 32 - tr_32 */
int t_32_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_32_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_32_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Y >= 3200 );
}

void t_32_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_2--;
}

void t_32_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_32_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 35 - tr_35 */
int t_35_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_5 >= 1 );
}

int t_35_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_35_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_X >= 3200 );
}

void t_35_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_5--;
}

void t_35_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_35_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 39 - tr_landing */
int t_39_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_39_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_39_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal3 == 1 );
}

void t_39_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_39_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_75++;
}

void t_39_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 43 - tr_takeOff */
int t_43_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_38 >= 1 );
}

int t_43_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_43_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal3 == 1 );
}

void t_43_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_38--;
}

void t_43_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_74++;
}

void t_43_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 48 - tr_48 */
int t_48_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_48_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_48_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal1 == 1 );
}

void t_48_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_48_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_46++;
}

void t_48_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 49 - tr_49 */
int t_49_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_46 >= 1 );
}

int t_49_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_49_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal1 == 0 );
}

void t_49_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_46--;
}

void t_49_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_49_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 54 - tr_54 */
int t_54_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_54_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_54_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal2 == 1 );
}

void t_54_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_54_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_47++;
}

void t_54_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 55 - tr_55 */
int t_55_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_47 >= 1 );
}

int t_55_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_55_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal2 == 0 );
}

void t_55_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_47--;
}

void t_55_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_55_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 61 - tr_61 */
int t_61_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_61_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_61_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal4 == 1 );
}

void t_61_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_61_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_60++;
}

void t_61_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 62 - tr_62 */
int t_62_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_60 >= 1 );
}

int t_62_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_62_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal4 == 0 );
}

void t_62_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_60--;
}

void t_62_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_62_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 68 - tr_68 */
int t_68_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_68_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_68_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal5 == 1 );
}

void t_68_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_68_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_67++;
}

void t_68_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 69 - tr_69 */
int t_69_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_67 >= 1 );
}

int t_69_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_69_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal5 == 0 );
}

void t_69_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_67--;
}

void t_69_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_69_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 76 - tr_76 */
int t_76_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_74 >= 1 );
}

int t_76_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_76_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal3 == 0 );
}

void t_76_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_74--;
}

void t_76_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_76_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 77 - tr_77 */
int t_77_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_75 >= 1 );
}

int t_77_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_77_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal3 == 0 );
}

void t_77_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_75--;
}

void t_77_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_38++;
}

void t_77_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 85 - tr_85 */
int t_85_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_3 >= 1 );
}

int t_85_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_85_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal6 == 1 );
}

void t_85_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3--;
}

void t_85_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_84++;
}

void t_85_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 86 - tr_86 */
int t_86_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_84 >= 1 );
}

int t_86_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_86_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal6 == 0 );
}

void t_86_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_84--;
}

void t_86_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_86_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 92 - tr_92 */
int t_92_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_60 >= 1 );
}

int t_92_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_92_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal7 == 1 );
}

void t_92_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_60--;
}

void t_92_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_91++;
}

void t_92_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 99 - tr_99 */
int t_99_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_91 >= 1 );
}

int t_99_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_99_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal4 == 0 );
}

void t_99_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_91--;
}

void t_99_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_99_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 102 - tr_102 */
int t_102_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_67 >= 1 );
}

int t_102_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_102_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal7 == 1 );
}

void t_102_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_67--;
}

void t_102_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_104++;
}

void t_102_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 103 - tr_103 */
int t_103_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_104 >= 1 );
}

int t_103_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_103_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal5 == 0 );
}

void t_103_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_104--;
}

void t_103_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_103_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 110 - tr_110 */
int t_110_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_46 >= 1 );
}

int t_110_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_110_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal7 == 1 );
}

void t_110_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_46--;
}

void t_110_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_109++;
}

void t_110_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 111 - tr_111 */
int t_111_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_109 >= 1 );
}

int t_111_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_111_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal1 == 0 );
}

void t_111_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_109--;
}

void t_111_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_111_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 117 - tr_117 */
int t_117_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_47 >= 1 );
}

int t_117_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_117_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal7 == 1 );
}

void t_117_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_47--;
}

void t_117_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_116++;
}

void t_117_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Transition 118 - tr_118 */
int t_118_enabled( Gyro_Project_NetMarking* prev,
                    Gyro_Project_NetMarking* avail )
{
    return ( avail->p_116 >= 1 );
}

int t_118_events( Gyro_Project_InputSignalEvents* events )
{
    return (  1  );
}

int t_118_guards( Gyro_Project_NetMarking* marking,
                   Gyro_Project_InputSignals* inputs,
                   Gyro_Project_PlaceOutputSignals* place_out,
                   Gyro_Project_EventOutputSignals* ev_out )
{
    return ( inputs->In_Signal2 == 0 );
}

void t_118_remove_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_116--;
}

void t_118_add_marks( Gyro_Project_NetMarking* marking )
{
    marking->p_3++;
}

void t_118_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out )
{
}


/* Input event processing: */
void Gyro_Project_GenerateInputSignalEvents(
        Gyro_Project_InputSignals *old_values,
        Gyro_Project_InputSignals *new_values,
        Gyro_Project_InputSignalEvents *events )
{
}

/* Output event processing: */
void Gyro_Project_GenerateEventOutputSignals(
    Gyro_Project_OutputSignalEvents *events,
    Gyro_Project_EventOutputSignals *signals )
{
}

/* Transition action processing: */
void Gyro_Project_GenerateTransitionActionOutputSignals(
    Gyro_Project_TransitionFiring *tfired,
    Gyro_Project_NetMarking *marking,
    Gyro_Project_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void Gyro_Project_GeneratePlaceOutputSignals(
    Gyro_Project_NetMarking *marking,
    Gyro_Project_InputSignals *inputs,
    Gyro_Project_PlaceOutputSignals *place_out,
    Gyro_Project_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    Gyro_Project_PlaceOutputSignals new_out = *place_out;
    
    /* Signal Out_TakeOffLand */
    new_val = 0;
    if( marking->p_3 > 0 ) { /* Place pl_Flying */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_75 > 0 ) { /* Place pl_Landing */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_74 > 0 ) { /* Place pl_TakeOff */
        exp_res = 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_TakeOffLand = 1;
    else if( new_val < 0 ) new_out.Out_TakeOffLand = 0;
    else new_out.Out_TakeOffLand = new_val;

    /* Signal Out_Foward */
    new_val = 0;
    if( marking->p_2 > 0 ) { /* Place pl_Foward */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Foward = 1;
    else if( new_val < 0 ) new_out.Out_Foward = 0;
    else new_out.Out_Foward = new_val;

    /* Signal Out_Backward */
    new_val = 0;
    if( marking->p_4 > 0 ) { /* Place pl_Backward */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Backward = 1;
    else if( new_val < 0 ) new_out.Out_Backward = 0;
    else new_out.Out_Backward = new_val;

    /* Signal Out_Left */
    new_val = 0;
    if( marking->p_5 > 0 ) { /* Place pl_left */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Left = 1;
    else if( new_val < 0 ) new_out.Out_Left = 0;
    else new_out.Out_Left = new_val;

    /* Signal Out_Right */
    new_val = 0;
    if( marking->p_6 > 0 ) { /* Place pl_right */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Right = 1;
    else if( new_val < 0 ) new_out.Out_Right = 0;
    else new_out.Out_Right = new_val;

    /* Signal Out_Up */
    new_val = 0;
    if( marking->p_60 > 0 ) { /* Place pl_Up */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Up = 1;
    else if( new_val < 0 ) new_out.Out_Up = 0;
    else new_out.Out_Up = new_val;

    /* Signal Out_Down */
    new_val = 0;
    if( marking->p_67 > 0 ) { /* Place pl_Down */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_Down = 1;
    else if( new_val < 0 ) new_out.Out_Down = 0;
    else new_out.Out_Down = new_val;

    /* Signal Out_RotateLeft */
    new_val = 0;
    if( marking->p_46 > 0 ) { /* Place pl_RotateLeft */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_RotateLeft = 1;
    else if( new_val < 0 ) new_out.Out_RotateLeft = 0;
    else new_out.Out_RotateLeft = new_val;

    /* Signal Out_RotateRight */
    new_val = 0;
    if( marking->p_47 > 0 ) { /* Place pl_RotateRight */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_RotateRight = 1;
    else if( new_val < 0 ) new_out.Out_RotateRight = 0;
    else new_out.Out_RotateRight = new_val;

    /* Signal Out_TakePhoto */
    new_val = 0;
    if( marking->p_84 > 0 ) { /* Place pl_takePhoto */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.Out_TakePhoto = 1;
    else if( new_val < 0 ) new_out.Out_TakePhoto = 0;
    else new_out.Out_TakePhoto = new_val;

    *place_out = new_out;
}

