/* Net Gyro_Project - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#ifndef __Gyro_Project_DEFS
#define __Gyro_Project_DEFS


#define TRACE_CONT_RUN       (-1)
#define TRACE_PAUSE          0
#define TRACE_SINGLE_STEP    1
#define TRACE_N_STEPS(n)     (n)

#define MODEL_NAME		Gyro_Project
#define MODEL_NAME_STR		"Gyro_Project"
#define MODEL_VERSION		"2016-03-02 15:53:29"
#define MODEL_N_INPUTS		9
#define MODEL_N_OUTPUTS		10
#define MODEL_N_PLACES		17
#define MODEL_N_TRANSITIONS	30

#ifdef __cplusplus
extern "C" {
#endif

extern int trace_control;

typedef struct {
    unsigned int p_2: 1; /* Place pl_Foward */
    unsigned int p_3: 1; /* Place pl_Flying */
    unsigned int p_4: 1; /* Place pl_Backward */
    unsigned int p_5: 1; /* Place pl_left */
    unsigned int p_6: 1; /* Place pl_right */
    unsigned int p_38: 1; /* Place pl_Land */
    unsigned int p_46: 1; /* Place pl_RotateLeft */
    unsigned int p_47: 1; /* Place pl_RotateRight */
    unsigned int p_60: 1; /* Place pl_Up */
    unsigned int p_67: 1; /* Place pl_Down */
    unsigned int p_74: 2; /* Place pl_TakeOff */
    unsigned int p_75: 1; /* Place pl_Landing */
    unsigned int p_84: 1; /* Place pl_takePhoto */
    unsigned int p_91: 2; /* Place pl_Wait */
    unsigned int p_104: 2; /* Place pl_Wait2 */
    unsigned int p_109: 1; /* Place pl_Wait3 */
    unsigned int p_116: 1; /* Place pl_Wait4 */
    unsigned int padding: 4;
} Gyro_Project_NetMarking;


typedef struct {
    unsigned int In_Y : 13;
    unsigned int In_X : 13;
    unsigned int In_Signal1 : 1;
    unsigned int In_Signal2 : 1;
    unsigned int In_Signal3 : 1;
    unsigned int In_Signal4 : 1;
    unsigned int In_Signal5 : 1;
    unsigned int In_Signal6 : 1;
    unsigned int In_Signal7 : 1;
} Gyro_Project_InputSignals;


typedef struct {
} Gyro_Project_InputSignalEvents;


typedef struct {
} Gyro_Project_OutputSignalEvents;


typedef struct {
    unsigned int Out_TakeOffLand : 1;
    unsigned int Out_Foward : 1;
    unsigned int Out_Backward : 1;
    unsigned int Out_Left : 1;
    unsigned int Out_Right : 1;
    unsigned int Out_Up : 1;
    unsigned int Out_Down : 1;
    unsigned int Out_RotateLeft : 1;
    unsigned int Out_RotateRight : 1;
    unsigned int Out_TakePhoto : 1;
} Gyro_Project_PlaceOutputSignals;


typedef struct {
} Gyro_Project_EventOutputSignals;


typedef struct {
    unsigned int t_7 : 1; /* tr_up */
    unsigned int t_10 : 1; /* tr_down */
    unsigned int t_13 : 1; /* tr_left */
    unsigned int t_16 : 1; /* tr_right */
    unsigned int t_26 : 1; /* tr_26 */
    unsigned int t_29 : 1; /* tr_29 */
    unsigned int t_32 : 1; /* tr_32 */
    unsigned int t_35 : 1; /* tr_35 */
    unsigned int t_39 : 1; /* tr_landing */
    unsigned int t_43 : 1; /* tr_takeOff */
    unsigned int t_48 : 1; /* tr_48 */
    unsigned int t_49 : 1; /* tr_49 */
    unsigned int t_54 : 1; /* tr_54 */
    unsigned int t_55 : 1; /* tr_55 */
    unsigned int t_61 : 1; /* tr_61 */
    unsigned int t_62 : 1; /* tr_62 */
    unsigned int t_68 : 1; /* tr_68 */
    unsigned int t_69 : 1; /* tr_69 */
    unsigned int t_76 : 1; /* tr_76 */
    unsigned int t_77 : 1; /* tr_77 */
    unsigned int t_85 : 1; /* tr_85 */
    unsigned int t_86 : 1; /* tr_86 */
    unsigned int t_92 : 1; /* tr_92 */
    unsigned int t_99 : 1; /* tr_99 */
    unsigned int t_102 : 1; /* tr_102 */
    unsigned int t_103 : 1; /* tr_103 */
    unsigned int t_110 : 1; /* tr_110 */
    unsigned int t_111 : 1; /* tr_111 */
    unsigned int t_117 : 1; /* tr_117 */
    unsigned int t_118 : 1; /* tr_118 */
    unsigned int count: 8;
} Gyro_Project_TransitionFiring;

/* Array declarations: */


/* Runtime text info: */
typedef struct {
#ifdef __cplusplus
    const
#endif
    char* name;
    int value;
} iopt_param_info;

extern iopt_param_info* get_Gyro_Project_InputInfo();
extern iopt_param_info* get_Gyro_Project_OutputInfo();
extern iopt_param_info* get_Gyro_Project_MarkingInfo();
extern iopt_param_info* get_Gyro_Project_TFiredInfo();
extern void force_Gyro_Project_Inputs( iopt_param_info fv[], Gyro_Project_InputSignals* in );
extern void force_Gyro_Project_Outputs( iopt_param_info fv[], Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void force_Gyro_Project_Marking( iopt_param_info fv[], Gyro_Project_NetMarking* m );


extern void createInitial_Gyro_Project_NetMarking( Gyro_Project_NetMarking* init_marking );
extern void createEmpty_Gyro_Project_NetMarking( Gyro_Project_NetMarking* empty_marking );
extern void add_Gyro_Project_NetMarkings( Gyro_Project_NetMarking* dest_marking, Gyro_Project_NetMarking* source_marking );

extern void init_Gyro_Project_OutputSignals( Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );

/* Transition 7 - tr_up */
extern int  t_7_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_7_events( Gyro_Project_InputSignalEvents* events );
extern int  t_7_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_7_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_7_add_marks( Gyro_Project_NetMarking* marking );
extern void t_7_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 10 - tr_down */
extern int  t_10_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_10_events( Gyro_Project_InputSignalEvents* events );
extern int  t_10_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_10_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_10_add_marks( Gyro_Project_NetMarking* marking );
extern void t_10_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 13 - tr_left */
extern int  t_13_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_13_events( Gyro_Project_InputSignalEvents* events );
extern int  t_13_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_13_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_13_add_marks( Gyro_Project_NetMarking* marking );
extern void t_13_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 16 - tr_right */
extern int  t_16_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_16_events( Gyro_Project_InputSignalEvents* events );
extern int  t_16_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_16_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_16_add_marks( Gyro_Project_NetMarking* marking );
extern void t_16_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 26 - tr_26 */
extern int  t_26_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_26_events( Gyro_Project_InputSignalEvents* events );
extern int  t_26_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_26_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_26_add_marks( Gyro_Project_NetMarking* marking );
extern void t_26_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 29 - tr_29 */
extern int  t_29_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_29_events( Gyro_Project_InputSignalEvents* events );
extern int  t_29_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_29_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_29_add_marks( Gyro_Project_NetMarking* marking );
extern void t_29_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 32 - tr_32 */
extern int  t_32_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_32_events( Gyro_Project_InputSignalEvents* events );
extern int  t_32_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_32_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_32_add_marks( Gyro_Project_NetMarking* marking );
extern void t_32_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 35 - tr_35 */
extern int  t_35_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_35_events( Gyro_Project_InputSignalEvents* events );
extern int  t_35_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_35_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_35_add_marks( Gyro_Project_NetMarking* marking );
extern void t_35_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 39 - tr_landing */
extern int  t_39_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_39_events( Gyro_Project_InputSignalEvents* events );
extern int  t_39_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_39_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_39_add_marks( Gyro_Project_NetMarking* marking );
extern void t_39_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 43 - tr_takeOff */
extern int  t_43_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_43_events( Gyro_Project_InputSignalEvents* events );
extern int  t_43_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_43_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_43_add_marks( Gyro_Project_NetMarking* marking );
extern void t_43_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 48 - tr_48 */
extern int  t_48_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_48_events( Gyro_Project_InputSignalEvents* events );
extern int  t_48_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_48_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_48_add_marks( Gyro_Project_NetMarking* marking );
extern void t_48_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 49 - tr_49 */
extern int  t_49_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_49_events( Gyro_Project_InputSignalEvents* events );
extern int  t_49_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_49_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_49_add_marks( Gyro_Project_NetMarking* marking );
extern void t_49_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 54 - tr_54 */
extern int  t_54_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_54_events( Gyro_Project_InputSignalEvents* events );
extern int  t_54_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_54_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_54_add_marks( Gyro_Project_NetMarking* marking );
extern void t_54_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 55 - tr_55 */
extern int  t_55_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_55_events( Gyro_Project_InputSignalEvents* events );
extern int  t_55_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_55_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_55_add_marks( Gyro_Project_NetMarking* marking );
extern void t_55_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 61 - tr_61 */
extern int  t_61_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_61_events( Gyro_Project_InputSignalEvents* events );
extern int  t_61_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_61_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_61_add_marks( Gyro_Project_NetMarking* marking );
extern void t_61_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 62 - tr_62 */
extern int  t_62_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_62_events( Gyro_Project_InputSignalEvents* events );
extern int  t_62_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_62_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_62_add_marks( Gyro_Project_NetMarking* marking );
extern void t_62_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 68 - tr_68 */
extern int  t_68_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_68_events( Gyro_Project_InputSignalEvents* events );
extern int  t_68_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_68_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_68_add_marks( Gyro_Project_NetMarking* marking );
extern void t_68_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 69 - tr_69 */
extern int  t_69_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_69_events( Gyro_Project_InputSignalEvents* events );
extern int  t_69_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_69_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_69_add_marks( Gyro_Project_NetMarking* marking );
extern void t_69_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 76 - tr_76 */
extern int  t_76_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_76_events( Gyro_Project_InputSignalEvents* events );
extern int  t_76_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_76_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_76_add_marks( Gyro_Project_NetMarking* marking );
extern void t_76_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 77 - tr_77 */
extern int  t_77_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_77_events( Gyro_Project_InputSignalEvents* events );
extern int  t_77_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_77_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_77_add_marks( Gyro_Project_NetMarking* marking );
extern void t_77_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 85 - tr_85 */
extern int  t_85_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_85_events( Gyro_Project_InputSignalEvents* events );
extern int  t_85_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_85_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_85_add_marks( Gyro_Project_NetMarking* marking );
extern void t_85_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 86 - tr_86 */
extern int  t_86_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_86_events( Gyro_Project_InputSignalEvents* events );
extern int  t_86_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_86_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_86_add_marks( Gyro_Project_NetMarking* marking );
extern void t_86_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 92 - tr_92 */
extern int  t_92_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_92_events( Gyro_Project_InputSignalEvents* events );
extern int  t_92_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_92_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_92_add_marks( Gyro_Project_NetMarking* marking );
extern void t_92_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 99 - tr_99 */
extern int  t_99_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_99_events( Gyro_Project_InputSignalEvents* events );
extern int  t_99_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_99_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_99_add_marks( Gyro_Project_NetMarking* marking );
extern void t_99_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 102 - tr_102 */
extern int  t_102_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_102_events( Gyro_Project_InputSignalEvents* events );
extern int  t_102_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_102_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_102_add_marks( Gyro_Project_NetMarking* marking );
extern void t_102_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 103 - tr_103 */
extern int  t_103_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_103_events( Gyro_Project_InputSignalEvents* events );
extern int  t_103_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_103_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_103_add_marks( Gyro_Project_NetMarking* marking );
extern void t_103_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 110 - tr_110 */
extern int  t_110_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_110_events( Gyro_Project_InputSignalEvents* events );
extern int  t_110_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_110_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_110_add_marks( Gyro_Project_NetMarking* marking );
extern void t_110_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 111 - tr_111 */
extern int  t_111_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_111_events( Gyro_Project_InputSignalEvents* events );
extern int  t_111_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_111_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_111_add_marks( Gyro_Project_NetMarking* marking );
extern void t_111_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 117 - tr_117 */
extern int  t_117_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_117_events( Gyro_Project_InputSignalEvents* events );
extern int  t_117_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_117_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_117_add_marks( Gyro_Project_NetMarking* marking );
extern void t_117_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
/* Transition 118 - tr_118 */
extern int  t_118_enabled( Gyro_Project_NetMarking* prev, Gyro_Project_NetMarking* avail );
extern int  t_118_events( Gyro_Project_InputSignalEvents* events );
extern int  t_118_guards( Gyro_Project_NetMarking* marking, Gyro_Project_InputSignals* inputs, Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* ev_out );
extern void t_118_remove_marks( Gyro_Project_NetMarking* marking );
extern void t_118_add_marks( Gyro_Project_NetMarking* marking );
extern void t_118_generate_output_events( Gyro_Project_OutputSignalEvents* ev_out );
extern void Gyro_Project_GenerateInputSignalEvents( Gyro_Project_InputSignals *old_values, Gyro_Project_InputSignals *new_values, Gyro_Project_InputSignalEvents *events );

extern void Gyro_Project_GenerateEventOutputSignals( Gyro_Project_OutputSignalEvents *events, Gyro_Project_EventOutputSignals *signals );

extern void Gyro_Project_GenerateTransitionActionOutputSignals( Gyro_Project_TransitionFiring *tfired, Gyro_Project_NetMarking *marking, Gyro_Project_EventOutputSignals *signals );

extern void Gyro_Project_GeneratePlaceOutputSignals( Gyro_Project_NetMarking *marking, Gyro_Project_InputSignals *inputs, Gyro_Project_PlaceOutputSignals *place_out, Gyro_Project_EventOutputSignals *ev_out );

extern void Gyro_Project_ExecutionStep( Gyro_Project_NetMarking *prev_marking, Gyro_Project_InputSignals *inputs, Gyro_Project_InputSignals *prev_in, Gyro_Project_PlaceOutputSignals *place_out, Gyro_Project_EventOutputSignals *ev_out );

extern void Gyro_Project_InitializeIO();
extern void Gyro_Project_GetInputSignals( Gyro_Project_InputSignals* inputs, Gyro_Project_InputSignalEvents* events );
extern void Gyro_Project_PutOutputSignals( Gyro_Project_PlaceOutputSignals* place_out, Gyro_Project_EventOutputSignals* event_out, Gyro_Project_OutputSignalEvents* events );
extern void Gyro_Project_LoopDelay();
extern int Gyro_Project_FinishExecution( Gyro_Project_NetMarking* marking );

extern Gyro_Project_NetMarking* get_Gyro_Project_NetMarking();
extern Gyro_Project_InputSignals* get_Gyro_Project_InputSignals();
extern Gyro_Project_PlaceOutputSignals* get_Gyro_Project_PlaceOutputSignals();
extern Gyro_Project_EventOutputSignals* get_Gyro_Project_EventOutputSignals();
extern Gyro_Project_TransitionFiring* get_Gyro_Project_TransitionFiring();

#ifdef __cplusplus
};
#endif


#endif
