/* Net Gyro_Project - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static Gyro_Project_TransitionFiring tfired;
    

void Gyro_Project_ExecutionStep(
     Gyro_Project_NetMarking *prev_marking,
     Gyro_Project_InputSignals *inputs,
     Gyro_Project_InputSignals *prev_in,
     Gyro_Project_PlaceOutputSignals *place_out,
     Gyro_Project_EventOutputSignals *ev_out )
{
    Gyro_Project_NetMarking add_marking;
    Gyro_Project_NetMarking avail_marking = *prev_marking;
    Gyro_Project_InputSignalEvents input_events;
    Gyro_Project_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_Gyro_Project_NetMarking( &add_marking );
    Gyro_Project_GetInputSignals( inputs, &input_events );
    Gyro_Project_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition tr_up */
    if( t_7_enabled( prev_marking, &avail_marking ) &&
        t_7_events( &input_events ) &&
        t_7_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_7 = 1;
        t_7_remove_marks( &avail_marking );
        t_7_add_marks( &add_marking );
        t_7_generate_output_events( &output_events );
    }

    /* Transition tr_down */
    if( t_10_enabled( prev_marking, &avail_marking ) &&
        t_10_events( &input_events ) &&
        t_10_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_10 = 1;
        t_10_remove_marks( &avail_marking );
        t_10_add_marks( &add_marking );
        t_10_generate_output_events( &output_events );
    }

    /* Transition tr_left */
    if( t_13_enabled( prev_marking, &avail_marking ) &&
        t_13_events( &input_events ) &&
        t_13_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_13 = 1;
        t_13_remove_marks( &avail_marking );
        t_13_add_marks( &add_marking );
        t_13_generate_output_events( &output_events );
    }

    /* Transition tr_right */
    if( t_16_enabled( prev_marking, &avail_marking ) &&
        t_16_events( &input_events ) &&
        t_16_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_16 = 1;
        t_16_remove_marks( &avail_marking );
        t_16_add_marks( &add_marking );
        t_16_generate_output_events( &output_events );
    }

    /* Transition tr_26 */
    if( t_26_enabled( prev_marking, &avail_marking ) &&
        t_26_events( &input_events ) &&
        t_26_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_26 = 1;
        t_26_remove_marks( &avail_marking );
        t_26_add_marks( &add_marking );
        t_26_generate_output_events( &output_events );
    }

    /* Transition tr_29 */
    if( t_29_enabled( prev_marking, &avail_marking ) &&
        t_29_events( &input_events ) &&
        t_29_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_29 = 1;
        t_29_remove_marks( &avail_marking );
        t_29_add_marks( &add_marking );
        t_29_generate_output_events( &output_events );
    }

    /* Transition tr_32 */
    if( t_32_enabled( prev_marking, &avail_marking ) &&
        t_32_events( &input_events ) &&
        t_32_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_32 = 1;
        t_32_remove_marks( &avail_marking );
        t_32_add_marks( &add_marking );
        t_32_generate_output_events( &output_events );
    }

    /* Transition tr_35 */
    if( t_35_enabled( prev_marking, &avail_marking ) &&
        t_35_events( &input_events ) &&
        t_35_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_35 = 1;
        t_35_remove_marks( &avail_marking );
        t_35_add_marks( &add_marking );
        t_35_generate_output_events( &output_events );
    }

    /* Transition tr_landing */
    if( t_39_enabled( prev_marking, &avail_marking ) &&
        t_39_events( &input_events ) &&
        t_39_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_39 = 1;
        t_39_remove_marks( &avail_marking );
        t_39_add_marks( &add_marking );
        t_39_generate_output_events( &output_events );
    }

    /* Transition tr_takeOff */
    if( t_43_enabled( prev_marking, &avail_marking ) &&
        t_43_events( &input_events ) &&
        t_43_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_43 = 1;
        t_43_remove_marks( &avail_marking );
        t_43_add_marks( &add_marking );
        t_43_generate_output_events( &output_events );
    }

    /* Transition tr_48 */
    if( t_48_enabled( prev_marking, &avail_marking ) &&
        t_48_events( &input_events ) &&
        t_48_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_48 = 1;
        t_48_remove_marks( &avail_marking );
        t_48_add_marks( &add_marking );
        t_48_generate_output_events( &output_events );
    }

    /* Transition tr_49 */
    if( t_49_enabled( prev_marking, &avail_marking ) &&
        t_49_events( &input_events ) &&
        t_49_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_49 = 1;
        t_49_remove_marks( &avail_marking );
        t_49_add_marks( &add_marking );
        t_49_generate_output_events( &output_events );
    }

    /* Transition tr_54 */
    if( t_54_enabled( prev_marking, &avail_marking ) &&
        t_54_events( &input_events ) &&
        t_54_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_54 = 1;
        t_54_remove_marks( &avail_marking );
        t_54_add_marks( &add_marking );
        t_54_generate_output_events( &output_events );
    }

    /* Transition tr_55 */
    if( t_55_enabled( prev_marking, &avail_marking ) &&
        t_55_events( &input_events ) &&
        t_55_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_55 = 1;
        t_55_remove_marks( &avail_marking );
        t_55_add_marks( &add_marking );
        t_55_generate_output_events( &output_events );
    }

    /* Transition tr_61 */
    if( t_61_enabled( prev_marking, &avail_marking ) &&
        t_61_events( &input_events ) &&
        t_61_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_61 = 1;
        t_61_remove_marks( &avail_marking );
        t_61_add_marks( &add_marking );
        t_61_generate_output_events( &output_events );
    }

    /* Transition tr_62 */
    if( t_62_enabled( prev_marking, &avail_marking ) &&
        t_62_events( &input_events ) &&
        t_62_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_62 = 1;
        t_62_remove_marks( &avail_marking );
        t_62_add_marks( &add_marking );
        t_62_generate_output_events( &output_events );
    }

    /* Transition tr_68 */
    if( t_68_enabled( prev_marking, &avail_marking ) &&
        t_68_events( &input_events ) &&
        t_68_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_68 = 1;
        t_68_remove_marks( &avail_marking );
        t_68_add_marks( &add_marking );
        t_68_generate_output_events( &output_events );
    }

    /* Transition tr_69 */
    if( t_69_enabled( prev_marking, &avail_marking ) &&
        t_69_events( &input_events ) &&
        t_69_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_69 = 1;
        t_69_remove_marks( &avail_marking );
        t_69_add_marks( &add_marking );
        t_69_generate_output_events( &output_events );
    }

    /* Transition tr_76 */
    if( t_76_enabled( prev_marking, &avail_marking ) &&
        t_76_events( &input_events ) &&
        t_76_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_76 = 1;
        t_76_remove_marks( &avail_marking );
        t_76_add_marks( &add_marking );
        t_76_generate_output_events( &output_events );
    }

    /* Transition tr_77 */
    if( t_77_enabled( prev_marking, &avail_marking ) &&
        t_77_events( &input_events ) &&
        t_77_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_77 = 1;
        t_77_remove_marks( &avail_marking );
        t_77_add_marks( &add_marking );
        t_77_generate_output_events( &output_events );
    }

    /* Transition tr_85 */
    if( t_85_enabled( prev_marking, &avail_marking ) &&
        t_85_events( &input_events ) &&
        t_85_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_85 = 1;
        t_85_remove_marks( &avail_marking );
        t_85_add_marks( &add_marking );
        t_85_generate_output_events( &output_events );
    }

    /* Transition tr_86 */
    if( t_86_enabled( prev_marking, &avail_marking ) &&
        t_86_events( &input_events ) &&
        t_86_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_86 = 1;
        t_86_remove_marks( &avail_marking );
        t_86_add_marks( &add_marking );
        t_86_generate_output_events( &output_events );
    }

    /* Transition tr_92 */
    if( t_92_enabled( prev_marking, &avail_marking ) &&
        t_92_events( &input_events ) &&
        t_92_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_92 = 1;
        t_92_remove_marks( &avail_marking );
        t_92_add_marks( &add_marking );
        t_92_generate_output_events( &output_events );
    }

    /* Transition tr_99 */
    if( t_99_enabled( prev_marking, &avail_marking ) &&
        t_99_events( &input_events ) &&
        t_99_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_99 = 1;
        t_99_remove_marks( &avail_marking );
        t_99_add_marks( &add_marking );
        t_99_generate_output_events( &output_events );
    }

    /* Transition tr_102 */
    if( t_102_enabled( prev_marking, &avail_marking ) &&
        t_102_events( &input_events ) &&
        t_102_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_102 = 1;
        t_102_remove_marks( &avail_marking );
        t_102_add_marks( &add_marking );
        t_102_generate_output_events( &output_events );
    }

    /* Transition tr_103 */
    if( t_103_enabled( prev_marking, &avail_marking ) &&
        t_103_events( &input_events ) &&
        t_103_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_103 = 1;
        t_103_remove_marks( &avail_marking );
        t_103_add_marks( &add_marking );
        t_103_generate_output_events( &output_events );
    }

    /* Transition tr_110 */
    if( t_110_enabled( prev_marking, &avail_marking ) &&
        t_110_events( &input_events ) &&
        t_110_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_110 = 1;
        t_110_remove_marks( &avail_marking );
        t_110_add_marks( &add_marking );
        t_110_generate_output_events( &output_events );
    }

    /* Transition tr_111 */
    if( t_111_enabled( prev_marking, &avail_marking ) &&
        t_111_events( &input_events ) &&
        t_111_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_111 = 1;
        t_111_remove_marks( &avail_marking );
        t_111_add_marks( &add_marking );
        t_111_generate_output_events( &output_events );
    }

    /* Transition tr_117 */
    if( t_117_enabled( prev_marking, &avail_marking ) &&
        t_117_events( &input_events ) &&
        t_117_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_117 = 1;
        t_117_remove_marks( &avail_marking );
        t_117_add_marks( &add_marking );
        t_117_generate_output_events( &output_events );
    }

    /* Transition tr_118 */
    if( t_118_enabled( prev_marking, &avail_marking ) &&
        t_118_events( &input_events ) &&
        t_118_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_118 = 1;
        t_118_remove_marks( &avail_marking );
        t_118_add_marks( &add_marking );
        t_118_generate_output_events( &output_events );
    }

    add_Gyro_Project_NetMarkings( &avail_marking, &add_marking );

    Gyro_Project_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    Gyro_Project_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    Gyro_Project_GenerateEventOutputSignals( &output_events, ev_out );
    Gyro_Project_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

Gyro_Project_TransitionFiring* get_Gyro_Project_TransitionFiring()
{
    return &tfired;
}

