/* Net Gyro_Project - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include <stdlib.h>
#include "net_types.h"


#if defined(HTTP_SERVER) || defined(DBG_INFO)

static iopt_param_info Gyro_Project_input_info[] = {
    { "In_Y", 0 },
    { "In_X", 0 },
    { "In_Signal1", 0 },
    { "In_Signal2", 0 },
    { "In_Signal3", 0 },
    { "In_Signal4", 0 },
    { "In_Signal5", 0 },
    { "In_Signal6", 0 },
    { "In_Signal7", 0 },
    { NULL, 0 }
};

static iopt_param_info Gyro_Project_output_info[] = {
    { "Out_TakeOffLand", 0 },
    { "Out_Foward", 0 },
    { "Out_Backward", 0 },
    { "Out_Left", 0 },
    { "Out_Right", 0 },
    { "Out_Up", 0 },
    { "Out_Down", 0 },
    { "Out_RotateLeft", 0 },
    { "Out_RotateRight", 0 },
    { "Out_TakePhoto", 0 },
    { NULL, 0 }
};

static iopt_param_info Gyro_Project_marking_info[] = {
    { "p_2", 0 },
    { "p_3", 0 },
    { "p_4", 0 },
    { "p_5", 0 },
    { "p_6", 0 },
    { "p_38", 0 },
    { "p_46", 0 },
    { "p_47", 0 },
    { "p_60", 0 },
    { "p_67", 0 },
    { "p_74", 0 },
    { "p_75", 0 },
    { "p_84", 0 },
    { "p_91", 0 },
    { "p_104", 0 },
    { "p_109", 0 },
    { "p_116", 0 },
    { NULL, 0 }
};

static iopt_param_info Gyro_Project_tfired_info[] = {
    { "t_7", 0 },
    { "t_10", 0 },
    { "t_13", 0 },
    { "t_16", 0 },
    { "t_26", 0 },
    { "t_29", 0 },
    { "t_32", 0 },
    { "t_35", 0 },
    { "t_39", 0 },
    { "t_43", 0 },
    { "t_48", 0 },
    { "t_49", 0 },
    { "t_54", 0 },
    { "t_55", 0 },
    { "t_61", 0 },
    { "t_62", 0 },
    { "t_68", 0 },
    { "t_69", 0 },
    { "t_76", 0 },
    { "t_77", 0 },
    { "t_85", 0 },
    { "t_86", 0 },
    { "t_92", 0 },
    { "t_99", 0 },
    { "t_102", 0 },
    { "t_103", 0 },
    { "t_110", 0 },
    { "t_111", 0 },
    { "t_117", 0 },
    { "t_118", 0 },
    { NULL, 0 }
};

iopt_param_info* get_Gyro_Project_InputInfo()
{
    Gyro_Project_InputSignals* inputs = get_Gyro_Project_InputSignals();
    Gyro_Project_input_info[0].value = inputs->In_Y;
    Gyro_Project_input_info[1].value = inputs->In_X;
    Gyro_Project_input_info[2].value = inputs->In_Signal1;
    Gyro_Project_input_info[3].value = inputs->In_Signal2;
    Gyro_Project_input_info[4].value = inputs->In_Signal3;
    Gyro_Project_input_info[5].value = inputs->In_Signal4;
    Gyro_Project_input_info[6].value = inputs->In_Signal5;
    Gyro_Project_input_info[7].value = inputs->In_Signal6;
    Gyro_Project_input_info[8].value = inputs->In_Signal7;
    return Gyro_Project_input_info;
}

iopt_param_info* get_Gyro_Project_OutputInfo()
{
    Gyro_Project_PlaceOutputSignals* place_out = get_Gyro_Project_PlaceOutputSignals();
    Gyro_Project_EventOutputSignals* ev_out = get_Gyro_Project_EventOutputSignals();
    Gyro_Project_output_info[0].value = place_out->Out_TakeOffLand;
    Gyro_Project_output_info[1].value = place_out->Out_Foward;
    Gyro_Project_output_info[2].value = place_out->Out_Backward;
    Gyro_Project_output_info[3].value = place_out->Out_Left;
    Gyro_Project_output_info[4].value = place_out->Out_Right;
    Gyro_Project_output_info[5].value = place_out->Out_Up;
    Gyro_Project_output_info[6].value = place_out->Out_Down;
    Gyro_Project_output_info[7].value = place_out->Out_RotateLeft;
    Gyro_Project_output_info[8].value = place_out->Out_RotateRight;
    Gyro_Project_output_info[9].value = place_out->Out_TakePhoto;
    return Gyro_Project_output_info;
}

iopt_param_info* get_Gyro_Project_MarkingInfo()
{
    Gyro_Project_NetMarking* marking = get_Gyro_Project_NetMarking();
    Gyro_Project_marking_info[0].value = marking->p_2;
    Gyro_Project_marking_info[1].value = marking->p_3;
    Gyro_Project_marking_info[2].value = marking->p_4;
    Gyro_Project_marking_info[3].value = marking->p_5;
    Gyro_Project_marking_info[4].value = marking->p_6;
    Gyro_Project_marking_info[5].value = marking->p_38;
    Gyro_Project_marking_info[6].value = marking->p_46;
    Gyro_Project_marking_info[7].value = marking->p_47;
    Gyro_Project_marking_info[8].value = marking->p_60;
    Gyro_Project_marking_info[9].value = marking->p_67;
    Gyro_Project_marking_info[10].value = marking->p_74;
    Gyro_Project_marking_info[11].value = marking->p_75;
    Gyro_Project_marking_info[12].value = marking->p_84;
    Gyro_Project_marking_info[13].value = marking->p_91;
    Gyro_Project_marking_info[14].value = marking->p_104;
    Gyro_Project_marking_info[15].value = marking->p_109;
    Gyro_Project_marking_info[16].value = marking->p_116;
    return Gyro_Project_marking_info;
}

void force_Gyro_Project_Inputs( iopt_param_info fv[],
        Gyro_Project_InputSignals* in )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, Gyro_Project_input_info[0].name ) == 0 )
           in->In_Y = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[1].name ) == 0 )
           in->In_X = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[2].name ) == 0 )
           in->In_Signal1 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[3].name ) == 0 )
           in->In_Signal2 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[4].name ) == 0 )
           in->In_Signal3 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[5].name ) == 0 )
           in->In_Signal4 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[6].name ) == 0 )
           in->In_Signal5 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[7].name ) == 0 )
           in->In_Signal6 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_input_info[8].name ) == 0 )
           in->In_Signal7 = fv[i].value;
    }
}

void force_Gyro_Project_Outputs( iopt_param_info fv[],
        Gyro_Project_PlaceOutputSignals* place_out,
        Gyro_Project_EventOutputSignals* ev_out )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, Gyro_Project_output_info[0].name ) == 0 )
           place_out->Out_TakeOffLand = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[1].name ) == 0 )
           place_out->Out_Foward = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[2].name ) == 0 )
           place_out->Out_Backward = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[3].name ) == 0 )
           place_out->Out_Left = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[4].name ) == 0 )
           place_out->Out_Right = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[5].name ) == 0 )
           place_out->Out_Up = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[6].name ) == 0 )
           place_out->Out_Down = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[7].name ) == 0 )
           place_out->Out_RotateLeft = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[8].name ) == 0 )
           place_out->Out_RotateRight = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_output_info[9].name ) == 0 )
           place_out->Out_TakePhoto = fv[i].value;
    }
}

void force_Gyro_Project_Marking( iopt_param_info fv[],
        Gyro_Project_NetMarking* m )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, Gyro_Project_marking_info[0].name ) == 0 )
           m->p_2 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[1].name ) == 0 )
           m->p_3 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[2].name ) == 0 )
           m->p_4 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[3].name ) == 0 )
           m->p_5 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[4].name ) == 0 )
           m->p_6 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[5].name ) == 0 )
           m->p_38 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[6].name ) == 0 )
           m->p_46 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[7].name ) == 0 )
           m->p_47 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[8].name ) == 0 )
           m->p_60 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[9].name ) == 0 )
           m->p_67 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[10].name ) == 0 )
           m->p_74 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[11].name ) == 0 )
           m->p_75 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[12].name ) == 0 )
           m->p_84 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[13].name ) == 0 )
           m->p_91 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[14].name ) == 0 )
           m->p_104 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[15].name ) == 0 )
           m->p_109 = fv[i].value;
        else if( strcmp( fv[i].name, Gyro_Project_marking_info[16].name ) == 0 )
           m->p_116 = fv[i].value;
    }
}

iopt_param_info* get_Gyro_Project_TFiredInfo()
{
    Gyro_Project_TransitionFiring* tfired = get_Gyro_Project_TransitionFiring();
    Gyro_Project_tfired_info[0].value = tfired->t_7;
    Gyro_Project_tfired_info[1].value = tfired->t_10;
    Gyro_Project_tfired_info[2].value = tfired->t_13;
    Gyro_Project_tfired_info[3].value = tfired->t_16;
    Gyro_Project_tfired_info[4].value = tfired->t_26;
    Gyro_Project_tfired_info[5].value = tfired->t_29;
    Gyro_Project_tfired_info[6].value = tfired->t_32;
    Gyro_Project_tfired_info[7].value = tfired->t_35;
    Gyro_Project_tfired_info[8].value = tfired->t_39;
    Gyro_Project_tfired_info[9].value = tfired->t_43;
    Gyro_Project_tfired_info[10].value = tfired->t_48;
    Gyro_Project_tfired_info[11].value = tfired->t_49;
    Gyro_Project_tfired_info[12].value = tfired->t_54;
    Gyro_Project_tfired_info[13].value = tfired->t_55;
    Gyro_Project_tfired_info[14].value = tfired->t_61;
    Gyro_Project_tfired_info[15].value = tfired->t_62;
    Gyro_Project_tfired_info[16].value = tfired->t_68;
    Gyro_Project_tfired_info[17].value = tfired->t_69;
    Gyro_Project_tfired_info[18].value = tfired->t_76;
    Gyro_Project_tfired_info[19].value = tfired->t_77;
    Gyro_Project_tfired_info[20].value = tfired->t_85;
    Gyro_Project_tfired_info[21].value = tfired->t_86;
    Gyro_Project_tfired_info[22].value = tfired->t_92;
    Gyro_Project_tfired_info[23].value = tfired->t_99;
    Gyro_Project_tfired_info[24].value = tfired->t_102;
    Gyro_Project_tfired_info[25].value = tfired->t_103;
    Gyro_Project_tfired_info[26].value = tfired->t_110;
    Gyro_Project_tfired_info[27].value = tfired->t_111;
    Gyro_Project_tfired_info[28].value = tfired->t_117;
    Gyro_Project_tfired_info[29].value = tfired->t_118;
    return Gyro_Project_tfired_info;
}

#endif
