/* Net Gyro_Project - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include "net_types.h"


int trace_control = TRACE_CONT_RUN;

extern void httpServer_init();
extern void httpServer_getRequest();
extern void httpServer_sendResponse();
extern void httpServer_disconnectClient();
extern void httpServer_checkBreakPoints();
extern void httpServer_finish();

static Gyro_Project_NetMarking marking;
static Gyro_Project_InputSignals inputs, prev_inputs;
static Gyro_Project_PlaceOutputSignals place_out;
static Gyro_Project_EventOutputSignals ev_out;

void setup()
{
    createInitial_Gyro_Project_NetMarking( &marking );
    init_Gyro_Project_OutputSignals( &place_out, &ev_out );
    Gyro_Project_InitializeIO();
    Gyro_Project_GetInputSignals( &prev_inputs, NULL );
#ifdef HTTP_SERVER
    httpServer_init();
#endif
}

void loop()
{
#ifdef HTTP_SERVER
    httpServer_getRequest();
#endif

    if( trace_control != TRACE_PAUSE )
        Gyro_Project_ExecutionStep( &marking, &inputs, &prev_inputs, &place_out, &ev_out );
    else Gyro_Project_GetInputSignals( &inputs, NULL );
    if( trace_control > TRACE_PAUSE ) --trace_control;

#ifdef HTTP_SERVER
    httpServer_sendResponse();
#endif

    Gyro_Project_LoopDelay();

#ifdef HTTP_SERVER
    httpServer_disconnectClient();
    httpServer_checkBreakPoints();
#endif
}

#ifndef ARDUINO
int main()
{
    setup();

    do loop();
    while( Gyro_Project_FinishExecution( &marking ) == 0 );

#ifdef HTTP_SERVER
    httpServer_finish();
#endif

    return 0;
}
#endif


Gyro_Project_NetMarking* get_Gyro_Project_NetMarking()
{
    return &marking;
}

Gyro_Project_InputSignals* get_Gyro_Project_InputSignals()
{
    return &inputs;
}

Gyro_Project_PlaceOutputSignals* get_Gyro_Project_PlaceOutputSignals()
{
    return &place_out;
}

Gyro_Project_EventOutputSignals* get_Gyro_Project_EventOutputSignals()
{
    return &ev_out;
}

